-- MySQL Script generated by MySQL Workbench
-- Sat Mar  5 18:45:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema subquerry
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema subquerry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `subquerry` DEFAULT CHARACTER SET utf8 ;
USE `subquerry` ;

-- -----------------------------------------------------
-- Table `subquerry`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subquerry`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO estado (nome,sigla) VALUES ('PARANÁ','PR'), ('SÃO PAULO','SP'), ('MATO GROSSO','MT'), ('BAHIA','BA'), ('RIO GRANDE DO SUL','RS');

-- -----------------------------------------------------
-- Table `subquerry`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subquerry`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado_idx` (`estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`estado_id`)
    REFERENCES `subquerry`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO cidade (nome,estado_id) VALUES ('APUCARANA',1), ('BAURU',2), ('ITABUNA',4), ('JUNDIAÍ',2), ('LONDRINA',1), ('SALVADOR',4);

SELECT id,nome,estado_id
FROM cidade;

SELECT nome FROM estado;

SELECT nome FROM estado WHERE id = 1;

SELECT nome FROM estado WHERE id = 4;

SELECT id,nome,(SELECT nome FROM estado WHERE id = estado_id) estado FROM cidade;

SELECT * FROM estado;

SELECT id,nome,sigla FROM estado;

SELECT nome FROM cidade WHERE estado_id = 1;

SELECT nome FROM cidade WHERE estado_id = 2;

SELECT estado.id,estado.nome,estado.sigla,(SELECT count(cidade.nome) FROM cidade WHERE cidade.estado_id = estado.id),(SELECT group_concat(cidade.nome) FROM cidade WHERE cidade.estado_id = estado.id) FROM estado;

SELECT mt.nome FROM (SELECT * FROM estado WHERE id > 1) mt;

SELECT mr.nest,qte,ncid
FROM
(SELECT e.id,e.nome nest,e.sigla,(SELECT count(c.nome) FROM cidade c WHERE c.estado_id = e.id) qte,(SELECT group_concat(c.nome) FROM cidade c WHERE c.estado_id = e.id) ncid FROM estado e) mr;

-- -----------------------------------------------------
-- Table `subquerry`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subquerry`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` CHAR(14) NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_cidade1_idx` (`cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `subquerry`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO cliente (nome,cidade_id) VALUES ('EDSON',1), ('TALITA',2), ('HADASSA',3), ('FABRÍCIA',4);

SELECT * FROM cliente;

-- -----------------------------------------------------
-- Table `subquerry`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subquerry`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(9) NULL,
  `data` DATE NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venda_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `subquerry`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO venda (cliente_id) VALUES (1), (1), (2), (3);

SELECT id,nome FROM cliente WHERE id IN (SELECT cliente_id FROM venda);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
