/**
CREATE VIEW nome_view AS select_statement;

A views pode utilizada para:
- Isolamento ou Segurança
**/
DESCRIBE ESTADO;

CREATE VIEW view_estado1 AS SELECT id,nome FROM estado;

ALTER TABLE ESTADO ADD COLUMN TESTE VARCHAR(10) NULL;

SELECT * FROM ESTADO;
SELECT * FROM view_estado;

INSERT INTO VIEW_ESTADO (NOME,SIGLA) VALUES ('PERNAMBUCO','EE');

UPDATE VIEW_ESTADO SET SIGLA='PE' WHERE NOME = 'PERNAMBUCO';

DELETE FROM VIEW_ESTADO WHERE NOME = 'PERNAMBUCO';

DESCRIBE VIEW_ESTADO;
DESCRIBE ESTADO;

SELECT ID,NOME,DATA_CADASTRO FROM VIEW_ESTADO;

SELECT * FROM CIDADE;

CREATE VIEW view_cidades_parana AS SELECT * FROM cidade WHERE estado_id = 1;

SELECT * FROM view_cidades_parana;

SELECT * FROM VIEW_CIDADES_PARANA WHERE ID >6;

SELECT vcp.nome, ve.sigla FROM view_estado ve, view_cidades_parana vcp WHERE ve.id = vcp.estado_id;

SELECT VCP.NOME 'NOME CIDADE', VE.SIGLA 'SIGLA ESTADO'
FROM VIEW_ESTADO VE, VIEW_CIDADES_PARANA VCP
WHERE VE.ID = VCP.ESTADO_ID;

SELECT ve.nome, c.nome FROM view_estado ve, cidade c WHERE ve.id = c.estado_id;

SELECT C.NOME 'NOME CIDADE', VE.SIGLA 'SIGLA ESTADO'
FROM VIEW_ESTADO VE, CIDADE C
WHERE VE.ID = C.ESTADO_ID;


/** - Simplificar o acesso  
CIDADES AGRUPADOS PELO ESTADO, 
NOMES DAS CIDADES POR ESTADO,
QUANTIDADE DE CIDADES POR ESTADO,
QUE SEJAM DA REGIÃO SUL, 
MAS SOMENTE DOS ESTADOS QUE POSSUEM MAIS DE 2 CIDADES CADASTRADAS
**/

CREATE OR REPLACE VIEW view_group_estado AS
SELECT e.nome, group_concat(c.nome), count(c.id)
FROM estado e INNER JOIN cidade c ON e.id = c.estado_id 
WHERE e.nome IN ('PARANÁ','SANTA CATARINA','RIO GRANDE DO SUL')
GROUP BY e.id HAVING count(c.id) > 1;

SELECT * FROM view_group_estado;

CREATE OR REPLACE VIEW view_estado AS SELECT * FROM estado;

DESCRIBE view_estado;

CREATE OR REPLACE VIEW VIEW_GROUP_ESTADO AS 
SELECT E.NOME 'ESTADO', GROUP_CONCAT(C.NOME) 'CIDADES', COUNT(C.ID) 'QUANTIDADE CIDADES'
FROM ESTADO E 
INNER JOIN CIDADE C ON E.ID = C.ESTADO_ID 
WHERE  E.NOME IN ('PARANÁ', 'SANTA CATARINA', 'RIO GRANDE DO SUL')
GROUP BY E.ID;

SELECT * FROM VIEW_GROUP_ESTADO;

DROP VIEW VIEW_GROUP_ESTADO;





/** - para o Desempenho **/