-- MySQL Script generated by MySQL Workbench
-- Tue Feb 22 18:35:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_helio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_helio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_helio` DEFAULT CHARACTER SET utf8 ;
USE `projeto_helio` ;

-- -----------------------------------------------------
-- Table `projeto_helio`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `sigla` CHAR(2) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `status` CHAR(1) NOT NULL,
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado_idx` (`estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`estado_id`)
    REFERENCES `projeto_helio`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `CPF` CHAR(14) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`CPF` ASC) VISIBLE,
  INDEX `fk_funcionario_cidade1_idx` (`cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `projeto_helio`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `telefone` CHAR(14) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `funcionario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_telefone_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `projeto_helio`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `CPF_CNPJ` VARCHAR(18) NOT NULL,
  `telefone` CHAR(14) NOT NULL,
  `contato` VARCHAR(100) NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpfcnpj_UNIQUE` (`CPF_CNPJ` ASC) VISIBLE,
  INDEX `fk_cliente_cidade1_idx` (`cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `projeto_helio`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`fornecedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `CNPJ` CHAR(18) NOT NULL,
  `telefone` CHAR(14) NOT NULL,
  `contato` VARCHAR(200) NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpfcnpj_UNIQUE` (`CNPJ` ASC) VISIBLE,
  INDEX `fk_cliente_cidade1_idx` (`cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_cidade10`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `projeto_helio`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desconto` DECIMAL(9,2) NULL,
  `total` DECIMAL(9,2) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cliente_id` INT NOT NULL,
  `funcionario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venda_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_venda_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `projeto_helio`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `projeto_helio`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desconto` DECIMAL(9,2) NULL,
  `total` DECIMAL(9,2) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fornecedor_id` INT NOT NULL,
  `funcionario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compra_fornecedor1_idx` (`fornecedor_id` ASC) VISIBLE,
  INDEX `fk_compra_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  CONSTRAINT `fk_compra_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `projeto_helio`.`fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `projeto_helio`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `descricao` VARCHAR(200) NULL,
  `preco` DECIMAL(9,2) NULL,
  `estoque` INT NULL,
  `status` CHAR(1) NULL DEFAULT 'A',
  `data_cadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `produtocol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`item_venda` (
  `venda_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco` DECIMAL(9,2) NOT NULL,
  INDEX `fk_itemvenda_produto1_idx` (`produto_id` ASC) VISIBLE,
  INDEX `fk_itemvenda_venda1_idx` (`venda_id` ASC) VISIBLE,
  PRIMARY KEY (`venda_id`, `produto_id`),
  CONSTRAINT `fk_itemvenda_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `projeto_helio`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemvenda_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `projeto_helio`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`item_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`item_compra` (
  `compra_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco` DECIMAL(9,2) NOT NULL,
  INDEX `fk_itemcompra_produto1_idx` (`produto_id` ASC) VISIBLE,
  INDEX `fk_itemcompra_compra1_idx` (`compra_id` ASC) VISIBLE,
  PRIMARY KEY (`compra_id`, `produto_id`),
  CONSTRAINT `fk_itemcompra_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `projeto_helio`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemcompra_compra1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `projeto_helio`.`compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`produto_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`produto_categoria` (
  `categoria_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_produto_categoria_produto1_idx` (`produto_id` ASC) VISIBLE,
  INDEX `fk_produto_categoria_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  PRIMARY KEY (`categoria_id`, `produto_id`),
  CONSTRAINT `fk_produto_categoria_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `projeto_helio`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_categoria_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `projeto_helio`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`produto_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`produto_tipo` (
  `tipo_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_produto_tipo_produto1_idx` (`produto_id` ASC) VISIBLE,
  INDEX `fk_produto_tipo_tipo1_idx` (`tipo_id` ASC) VISIBLE,
  PRIMARY KEY (`tipo_id`, `produto_id`),
  CONSTRAINT `fk_produto_tipo_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `projeto_helio`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_tipo_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `projeto_helio`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`recebimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`recebimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `valor` DECIMAL(9,2) NOT NULL,
  `numero_parcela` INT NOT NULL,
  `desconto` DECIMAL(9,2) NULL,
  `juros` DECIMAL(9,2) NULL,
  `total_final` DECIMAL(9,2) NOT NULL,
  `venda_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recebimento_venda1_idx` (`venda_id` ASC) VISIBLE,
  CONSTRAINT `fk_recebimento_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `projeto_helio`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `valor` DECIMAL(9,2) NOT NULL,
  `numero_parcela` INT NOT NULL,
  `desconto` DECIMAL(9,2) NULL,
  `juros` DECIMAL(9,2) NULL,
  `total_final` DECIMAL(9,2) NOT NULL,
  `compra_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagamento_compra1_idx` (`compra_id` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_compra1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `projeto_helio`.`compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`caixa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  `saldo` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_helio`.`itemdecaixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_helio`.`itemdecaixa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `valor` DECIMAL(9,2) NOT NULL,
  `natureza` VARCHAR(200) NOT NULL,
  `hora` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `recebimento_id` INT NULL,
  `pagamento_id` INT NULL,
  `caixa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itemdecaixa_recebimento1_idx` (`recebimento_id` ASC) VISIBLE,
  INDEX `fk_itemdecaixa_pagamento1_idx` (`pagamento_id` ASC) VISIBLE,
  INDEX `fk_itemdecaixa_caixa1_idx` (`caixa_id` ASC) VISIBLE,
  CONSTRAINT `fk_itemdecaixa_recebimento1`
    FOREIGN KEY (`recebimento_id`)
    REFERENCES `projeto_helio`.`recebimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemdecaixa_pagamento1`
    FOREIGN KEY (`pagamento_id`)
    REFERENCES `projeto_helio`.`pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemdecaixa_caixa1`
    FOREIGN KEY (`caixa_id`)
    REFERENCES `projeto_helio`.`caixa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
